server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_db
    username: root
    password: 8av5mbxape@3byb
    driver-class-name: com.mysql.cj.jdbc.Driver


    jpa:
